
# Client
export FRACTAL_CLIENT_RELEASE=1231
export FRACTAL_CLIENT_GIT=2342

# server
export FRACTAL_SERVER_RELEASE=1231
export FRACTAL_SERVER_GIT=2342

# Tasks
export FRACTAL_TASKS_CORE_RELEASE=2342

# Web client
export FRACTAL_WEB_GIT=1221
