# syntax=docker/dockerfile:1

# selecting node image
FROM node:18-alpine3.17

# creating a workdir
WORKDIR /app

# installing bash shell
RUN apk add --no-cache bash

# running installation script
COPY config_client.sh .
RUN bash config_client.sh

# launch command
CMD ["npm", "run", "dev"]
