# syntax=docker/dockerfile:1

FROM fractal/web-base:1

ARG FRACTAL_SERVER_HOST

# Get fractal-web
ADD config.env .
COPY web/get_fractal_web.sh .
RUN bash get_fractal_web.sh

# moving to repository directory
WORKDIR /app/fractal-web/

# Installing dependencies and building
RUN npm install
RUN npm run build

# Set env variables
ENV FRACTAL_SERVER_HOST=${FRACTAL_SERVER_HOST}
ENV PUBLIC_FRACTAL_ADMIN_SUPPORT_EMAIL=
ENV PUBLIC_OAUTH_CLIENT_NAME=
ENV AUTH_COOKIE_DOMAIN=
ENV LOG_FILE=fractal-web.log
ENV FRACTAL_API_V1_MODE=exclude
ENV ORIGIN=http://localhost:5173
ENV PORT=5173

# Running
CMD node build
