# syntax=docker/dockerfile:1

FROM fractal/demos-v1-base:1

ADD config.env .

COPY demos-v1/get_fractal_client.sh .
RUN bash get_fractal_client.sh

COPY demos-v1/get_fractal_demos.sh .
RUN bash get_fractal_demos.sh

ADD config.env ./fractal-demos-v1/examples/config.env
COPY demos-v1/get_fractal_tasks_core.sh ./fractal-demos-v1/examples/get_fractal_tasks_core.sh
ADD demos-v1/fractal.env ./fractal-demos-v1/examples/.fractal.env
ADD demos-v1/run_demos.sh ./fractal-demos-v1/examples/run_demos.sh
