# syntax=docker/dockerfile:1

# selecting python image
FROM python:3.11-slim

# creating a workdir
WORKDIR /app

RUN apt-get update

# installing system packages, required for psycopg2
RUN apt-get -y install gcc postgresql postgresql-contrib libpq-dev

# installing system packages, required for fractal-tasks-core
RUN apt-get -y install libaec-dev

# required for healthcheck
RUN apt-get -y install curl
