# syntax=docker/dockerfile:1

# selecting python image
FROM python:3.11-slim

# creating a workdir
WORKDIR /app

# installing system packages, required for psycopg2
RUN apt-get update
RUN apt-get -y install gcc postgresql postgresql-contrib libpq-dev

# installing package
RUN pip install fractal-server[postgres,gunicorn]==1.3.5a1

# setting up DB configuration
COPY server/server.env ./.fractal_server.env

# launch command
CMD fractalctl set-db && fractalctl start --host 0.0.0.0 -p 8000
