# syntax=docker/dockerfile:1

FROM python:3.11-slim

WORKDIR /app

# Install system libraries
RUN apt-get update
RUN apt-get -y install gcc postgresql postgresql-contrib libpq-dev  # required for psycopg2
RUN apt-get -y install libaec-dev  # required for fractal-tasks-core
RUN apt-get -y install curl  # required for healthcheck
RUN apt-get -y install git  # required for installing server from git
RUN apt-get -y install freeglut3-dev  # required for napari-workflows?
