# syntax=docker/dockerfile:1

# Select Python image
FROM python:3.11-slim

# Install git
RUN apt-get update
RUN apt-get -y install git

# Install fractal-client
RUN pip install fractal-client==1.3.4a1

COPY demos/fractal.env ./.fractal.env
COPY demos/run_all_demos.sh ./run_all_demos.sh

RUN pip install zenodo-get

# launch command
CMD echo "START ALL" && pwd && ls -lash && bash run_all_demos.sh && echo "END ALL"
