# syntax=docker/dockerfile:1

FROM fractal/demos-base:1

# FIXME move to script and handle version
RUN pip install fractal-client==1.3.6

# FIXME move to script and handle version
RUN git clone https://github.com/fractal-analytics-platform/fractal-demos.git #

ADD demos/fractal.env ./fractal-demos/examples/.fractal.env
ADD demos/run_all_demos.sh ./fractal-demos/examples/run_all_demos.sh
