# syntax=docker/dockerfile:1

# Select Python image
FROM python:3.11-slim

# Install git
RUN apt-get update
RUN apt-get -y install git

# Install fractal-client
RUN pip install fractal-client==1.3.6a2
RUN pip install zenodo-get

RUN git clone https://github.com/fractal-analytics-platform/fractal-demos.git

ADD demos/fractal.env ./fractal-demos/examples/.fractal.env
ADD demos/run_all_demos.sh ./fractal-demos/examples/run_all_demos.sh

RUN mkdir /home/fractal-share
