# syntax=docker/dockerfile:1

FROM python:3.11-slim

# Install system libraries
RUN apt-get update
RUN apt-get -y install git  # required for installing client/tasks from git

# Install requirements for output-validation Python script
ADD demos/requirements-validation.txt ./requirements-validation.txt
RUN pip3 install -r requirements-validation.txt
