# syntax=docker/dockerfile:1

# selecting slurm master image
FROM rancavil/slurm-master:19.05.5-1

# copying config files
COPY slurm/slurm.conf /etc/slurm-llnl/
ADD slurm/sudoers /etc/sudoers

# adding slurm user
RUN useradd --uid 2000 -m fractal -s /usr/bin/bash -d /home/fractal && echo "fractal:fractal" | chpasswd

# entrypoint script, from the image
ENTRYPOINT ["/etc/slurm-llnl/docker-entrypoint.sh"]
