name: Build and Publish Docker Ubuntu22 Slurm Task Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Login
        env:
            GITHUB_ACTOR: ${{ github.actor }}
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u "${GITHUB_ACTOR}" --password-stdin
      - name: Build the Docker image Ubuntu22-slurm-fractal-tasks-core
        run:  docker build images/ubuntu22-slurm-tasks-core --tag ghcr.io/fractal-analytics-platform/ubuntu22-slurm-tasks-core:0.1
      - name: Push Docker Image
        run: docker push ghcr.io/fractal-analytics-platform/ubuntu22-slurm-tasks-core:0.1
