name: Test Fractal Demos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 23 * * 2,3,4"

jobs:

  tests-v2:
    timeout-minutes: 25
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Run demos
      run: cd testing && make run-demos-v2-github
