name: Test Fractal Demos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 23 * * 2,3,4"

permissions: {}

jobs:

  tests:
    timeout-minutes: 25
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - run: |
          cd testing
          make run-demos-github
