name: Test Fractal Demos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 23 * * 2,3,4"

permissions: {}

jobs:

  tests:
    timeout-minutes: 25
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - run: |
          cd testing
          make run-demos-github
