name: Test `examples/full-stack`

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 23 * * 2,3,4"

jobs:

  test-full-stack-example:
    timeout-minutes: 10
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Test `docker compose up`
      run: ./scripts/test_docker_compose_up_for_full_stack_example.sh
