# syntax=docker/dockerfile:1

FROM fractal/web-base:1

COPY web/install.sh .
RUN bash install.sh

# moving to repository directory
WORKDIR /app/fractal-web/

# setting up environment variables
COPY web/web.env ./.env

# Installing dependencies and building
RUN npm install
RUN npm run build

# Running
CMD ORIGIN=http://localhost:5173 PORT=5173 node build
