# syntax=docker/dockerfile:1

# selecting node image
FROM node:20-alpine3.17

# creating a workdir
WORKDIR /app

# installing bash shell
RUN apk add --no-cache bash

# installing selected program version
COPY web/install.sh .
RUN bash install.sh

# moving to repository directory
WORKDIR /app/fractal-web/

# setting up environment variables
COPY web/client.env ./.env

# Installing dependencies and building
RUN npm install
RUN npm run build

# Running
CMD ORIGIN=http://localhost:5173 PORT=5173 node build
