# syntax=docker/dockerfile:1

FROM python:3.11-slim

# Install system libraries
RUN apt-get update
RUN apt-get -y install git  # required for installing client/tasks from git
RUN apt-get -y install curl

# Install requirements for output-validation Python script
ADD demos-v2/requirements-validation.txt ./requirements-validation.txt
RUN python3 -m pip install -r requirements-validation.txt
