# syntax=docker/dockerfile:1

FROM fractal/demos-v2-base:1

ADD config.env .

COPY demos-v2/get_fractal_client.sh .
RUN bash get_fractal_client.sh

COPY demos-v2/get_fractal_demos.sh .
RUN bash get_fractal_demos.sh

ADD config.env ./fractal-demos-v2/examples/config.env
COPY demos-v2/get_fractal_tasks_core.sh ./fractal-demos-v2/examples/get_fractal_tasks_core.sh
ADD demos-v2/fractal.env ./fractal-demos-v2/examples/.fractal.env
ADD demos-v2/run_demos.sh ./fractal-demos-v2/examples/run_demos.sh
